spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/kamanote_tech?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:root123}
  redis:
    host: redis

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  path: /app/uploads
  url-prefix: http://39.106.98.5/images
